### ISSUE TITLE
parseInt "bug" causes a hang on message 008

### ISSUE THREAD

**Issue by stevecraig** [ollieparsley/node-lightwaverf#1]
When sending message 008 it is saved in the response map as "0" which causes it to hang.  The bug arises because parseInt("008") = 0 on nodejs (see discussion here https://groups.google.com/forum/#!msg/nodejs/H68wGy5x-OM/GJfqYoFcAj4J).

Simple fix is to add radix as second argument.  
parseInt("008",10) 
 
I'll submit a patch when I have finished experimenting.

**Comment by ollieparsley** [comment]
Fixed in master
